---

guild-ids:
  - 193593039650100397

cache:
  event-size: 16
  lookup-size: 384

logger:
  full-messages: false
  ignored-events: false

crawler:
  batch-size: 256
  queue-size: 32
  delays:
    yield: 0.5
    empty-source: 3600

bot:
  username: MyGreatBot#1000
  token: 'your discord token here'
  db-url: 'postgresql://username:password@localhost:5432/statbot'

