PostgreSQL:
  restart: always
  image: sameersbn/postgresql:9.6-2
  ports:
    - "5432:5432"
  environment:
    - DEBUG=false

    - PG_USERNAME=root
    - PG_PASSWORD=root

    - DB_USER=username
    - DB_PASS=password
    - DB_NAME=statbot
    - DB_TEMPLATE=

    - DB_EXTENSION=

    - REPLICATION_MODE=
    - REPLICATION_USER=
    - REPLICATION_PASS=
    - REPLICATION_SSLMODE=
  volumes:
    - ./docker/postgresql:/var/lib/postgresql
