language: python
dist: xenial
os: linux

stages:
  - black
  - test

python:
  - '3.6'
  - '3.7'
  - '3.8'
  - '3.8-dev'
  - 'nightly'

services:
  - postgresql

addons:
  postgresql: '9.5' # on_conflict requires 9.5+

jobs:
  include:
    - stage: black
      python: '3.8'
      script:
        - black --check futaba
  allow_failures:
    - python: 'nightly'
  fast_finish: true

cache: pip

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

before_script:
  - psql -f .travis/setup.sql -U postgres

script:
  # Run statbot tests
  - python3 -m unittest --verbose
  # Display all lints and a report
  - pylint --reports=yes futaba

notifications:
  email:
    on_success: change
    on_failure: always
