language: python
dist: trusty

python:
  - '3.6'
  - 'nightly'

sudo: false

cache: pip

install:
  - pip install --requirement requirements.txt
  - pip install pylint

script:
  - python3 -m unittest --verbose
  - pylint statbot

notifications:
  email:
    on_success: change
    on_failure: change

after_script:
  - bash travis_discord.sh
