language: python
dist: trusty

python:
  - '3.6'
  - 'nightly'

sudo: false

cache: pip

install:
  - pip install --quiet --requirement requirements.txt
  - pip install --quiet pylint

script:
  - python3 -m unittest --verbose
  - pylint statbot

notifications:
  email:
    on_success: change
    on_failure: change

after_script:
  - bash -c '$(curl -fsSL https://raw.githubusercontent.com/MaT1g3R/travis_discord/master/travis.sh)'
