language: python
dist: trusty

python:
  - '3.6'
  - 'nightly'

sudo: false

services:
  - postgresql

cache: pip

install:
  - pip install --requirement requirements.txt
  - pip install pylint

before_script:
  - psql -c 'create database statbot_test;' -U postgres
  - psql -c 'create user statbot_test; grant all privileges on database statbot_test to statbot_test;' -U postgres

script:
  - python3 -m unittest --verbose
  - pylint statbot

notifications:
  email:
    on_success: change
    on_failure: change

