language: python
dist: xenial
os: linux

python:
  - '3.6'
  - '3.7'
  - '3.8'
  - '3.8-dev'
  - 'nightly'

services:
  - postgresql

addons:
  postgresql: '9.5' # on_conflict requires 9.5+

jobs:
  include:
    - stage: black
      python: '3.8'
      script:
        - black --check futaba
  allow_failures:
    - python: 'nightly'

cache: pip

install:
  - pip install --requirement requirements.txt
  - pip install pylint

before_script:
  - psql -f .travis/setup.sql -U postgres

script:
  - python3 -m unittest --verbose
  - pylint statbot

notifications:
  email:
    on_success: change
    on_failure: always
